first_name = ('bukar')
print(first_name.capitalize())
print(first_name.casefold())
print(first_name.count('b')) 
print(first_name.endswith('b'))
print(first_name.upper())
print(first_name.lower())
print(first_name.index(''))
print(first_name.isdigit())
print(first_name.isprintable())
print(first_name.isdigit())
print(first_name.isalpha())
print(first_name.isalnum())
print(first_name.islower())
print(first_name.isnumeric())
print(first_name.replace('u', 'i'))
print(first_name.isdecimal())
print(first_name.find('u'))
print(first_name.isspace())
print(first_name.swapcase())


name = ("Umar")
print(name [-1])