num1 = 'Khaleel Dasuki'
print(num1.capitalize())
print(num1.casefold())
print(num1.center(20, '*'))
print(num1.count('k'))
print(num1.encode())
print(num1.endswith('l'))
print(num1.endswith('l'))
print(num1.index('K'))
print(num1.format_map('a'))
print(num1.format())
print(num1.find('a'))
print(num1.isalnum())
print(num1.isalpha())
print(num1.isascii())
print(num1.isdecimal())
print(num1.isdigit())
print(num1.isidentifier())
print(num1.islower())
print(num1.isnumeric())
print(num1.isprintable())
print(num1.isspace())
print(num1.istitle())
print(num1.isupper())
print(num1.join('Khaleel'))
print(num1.lower())
print(num1.lstrip())
print(num1.partition('Khaleel'))
print(num1.removeprefix('ha'))
print(num1.replace('a','b'))
print(num1.rfind('e'))
print(num1.rjust(20, 'b'))
print(num1.rsplit())
print(num1.rstrip())
print(num1.split())
print(num1.splitlines())
print(num1.startswith('D'))
print(num1.startswith('k'))
